### ISSUE TITLE
this tutorial using fragment

### ISSUE THREAD

**Issue by antoniomadrigal10** [dlukashev/AndroidSlidingUpPanel-foursquare-map-demo#1]
is this tutorial fully functional using fragments?

Im trying to set it up but the list its behaving strange!!

and im using mapview is there a problem whith that?

**Comment by garenacupson** [comment]
can you provide the java code using fragment

**Comment by dlukashev** [comment]
fixed in https://github.com/dlukashev/AndroidSlidingUpPanel-foursquare-map-demo/commit/7b869394e9d197e6f56a833804426577dcb8458a
