### ISSUE TITLE
No items or less item shows blank list.

### ISSUE THREAD

**Issue by rishabhsri20** [dlukashev/AndroidSlidingUpPanel-foursquare-map-demo#11]
If there are no items in the listview or the number is very less, the list layout show blank and it even scrolls which should not be there.

**Comment by dlukashev** [comment]
Are you kinnding me? :) just add view with white background under space view.

<RelativeLayout
            android:id="@+id/slidingContainer"
            android:layout_width="fill_parent"
            android:layout_height="fill_parent">

            <View
                android:id="@+id/transparentView"
                android:visibility="gone"
                android:layout_width="fill_parent"
                android:layout_height="@dimen/map_height"
                android:layout_alignParentTop="true"/>

            <View
                android:id="@+id/whiteSpaceView"
                android:background="@android:color/white"
                android:layout_marginTop="@dimen/map_height"
                android:layout_width="match_parent"
                android:layout_height="match_parent"/>

            <com.amberfog.mapslidingtest.app.LockableRecyclerView
                android:id="@android:id/list"
                android:cacheColorHint="@android:color/white"
                android:drawSelectorOnTop="true"
                android:dividerHeight="@dimen/divider_height"
                android:divider="@android:color/darker_gray"
                android:background="@android:color/transparent"
                android:layout_width="fill_parent"
                android:layout_height="fill_parent"
                android:layout_below="@id/transparentView"
                android:smoothScrollbar="false"/>
        </RelativeLayout>
