### ISSUE TITLE
Small listitem show map on the back of listview.

### ISSUE THREAD

**Issue by rishabhsri20** [dlukashev/AndroidSlidingUpPanel-foursquare-map-demo#12]
When the list item is very small and we have only one or 2 items in the arraylist then the map is shown in list background
![issue](https://cloud.githubusercontent.com/assets/6948436/10630756/cfdea7b8-77f6-11e5-9277-9f0ff23320dd.png)

**Comment by dlukashev** [comment]
Do you use the latest version? This was fixed in the latest commits
