### ISSUE TITLE
No items or small amount of items: Map does not resize

### ISSUE THREAD

**Issue by ashleypeacock** [dlukashev/AndroidSlidingUpPanel-foursquare-map-demo#5]
The map does not resize to the set map dimension on collapsing.

No code was editing from checking out the repository apart from below in which the problem can be recreated:

```java
for (int i = 0; i < 2; i++) {
            testData.add("Item " + i);
 }
```

**Comment by rishabhsri20** [comment]
Closed without a solution @ashleypeacock  did you find a way?

**Comment by ashleypeacock** [comment]
I found a solution to the caused effect without resizing. I added a fake footer view at the bottom to cover the map when there's less than 3 items. 
 This package is now being beautifully used in the android app Bubbal with some tweaks.  

Thanks for the reminder : do you want me to add  what we did?

**Comment by rishabhsri20** [comment]
yes please if you can. that would be really helpful.

-------- Original Message --------

**Comment by dlukashev** [comment]
see https://github.com/dlukashev/AndroidSlidingUpPanel-foursquare-map-demo/issues/11
