### ISSUE TITLE
Maven?

### ISSUE THREAD

**Issue by DroidDave** [dlukashev/AndroidSlidingUpPanel-foursquare-map-demo#6]
Would be nice to be able to add this using Maven dependancy.

**Comment by dlukashev** [comment]
Can you do that? :)

**Comment by DroidDave** [comment]
I will do this week. I am going to make a fork as there are some changes I
wish to make.

**Comment by dlukashev** [comment]
Could you also check my recent commit. I added fragments, fixed bugs, moved to the latest tools.

**Comment by DroidDave** [comment]
Ah OK yeah I will look over it. Are you using recyclers and eventbuses?

**Comment by dlukashev** [comment]
For this demo project - no! :)
