### ISSUE TITLE
SlidingUpPanel under mapfragment in one point 

### ISSUE THREAD

**Issue by klijakub** [dlukashev/AndroidSlidingUpPanel-foursquare-map-demo#7]
I made sliding panel using this repository https://github.com/dlukashev/AndroidSlidingUpPanel-foursquare-map-demo

However, it contains one certain bug which is not covered anywhere so I decided to ask community here as you may have some experience with that.

While scrolling, there is on point (top of listview) where my listview appears to hide beneath the map. If I scroll up again it gets back to work but it might be very confusing for users. Here is the screenshot:

http://i.stack.imgur.com/BMTxR.jpg

I heard that this is a common issue using this library, but unfortunately haven't found any solution. It certainly lays somewhere deep inside the class implementation, so I ask for some links or advices what should I do to get rid off this tedious issue.

Thanks in advance!

**Comment by klijakub** [comment]
Anyone of contributors have an idea how to fix it?

@johnjohndoe @dlukashev

**Comment by klijakub** [comment]
![bez tytulu](https://cloud.githubusercontent.com/assets/4997537/8267047/2bf2fe3e-1751-11e5-85f1-fdac58685731.png)

**Comment by dlukashev** [comment]
I think I fixed this a year ago. Let me check my production code

**Comment by klijakub** [comment]
@dlukashev thank you for your time! 

There is better description here 

http://stackoverflow.com/questions/30952174/sliding-up-panel-thin-line-sliding-panel-under-google-mapfragment

with a code fragment, but if you are able to fix it in your project then I would cover this in my program ;)

Thanks in advance!

**Comment by dlukashev** [comment]
fixed in https://github.com/dlukashev/AndroidSlidingUpPanel-foursquare-map-demo/commit/7b869394e9d197e6f56a833804426577dcb8458a
