### ISSUE TITLE
My Recyclerview approach - easy and minimalistic

### ISSUE THREAD

**Issue by jnsone11** [dlukashev/AndroidSlidingUpPanel-foursquare-map-demo#8]
As ListView is imho outdated here's my RecyclerView approach for everyone who's interested:

1. In your Layout, wrap slidingPanelLayout into a Framelayout or whatever.
2. Put Mapview or whatever View as first child of SlidingPanel
3. Put simple Recyclerview as second child of SlidingPanel
4. add a interface to your wrapping frameLayout that exposes OnInterceptTouch as a Listener

    @Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {

        if (onInterceptTouchListener != null){
            onInterceptTouchListener.onInterceptTouch(ev);
        }

        return super.onInterceptTouchEvent(ev);
    }

    private OnInterceptTouchListener onInterceptTouchListener;

    public void setOnInterceptTouchListener(OnInterceptTouchListener onInterceptTouchListener) {
        this.onInterceptTouchListener = onInterceptTouchListener;
    }

    public interface OnInterceptTouchListener{
        void onInterceptTouch(MotionEvent ev);
    }

5. here's the (very simple) magic:
In your Fragment or whatever mainView add the listener:

        frameLayout.setOnInterceptTouchListener(new FrameLayoutInterceptableInterface.OnInterceptTouchListener() {

            float actionDownY = 0;
            SlidingUpPanelLayout.PanelState actionDownState = SlidingUpPanelLayout.PanelState.COLLAPSED;

            @Override
            public void onInterceptTouch(MotionEvent ev) {

                if (ev.getAction() == MotionEvent.ACTION_DOWN) {
                    actionDownY = ev.getRawY();
                    actionDownState = sliding_layout.getPanelState();
                }

                if (ev.getAction() == MotionEvent.ACTION_MOVE){
                    if (actionDownState == SlidingUpPanelLayout.PanelState.EXPANDED && ev.getRawY() < actionDownY){
                        sliding_layout.requestDisallowInterceptTouchEvent(true);
                    } else if (actionDownState == SlidingUpPanelLayout.PanelState.EXPANDED && ultimate_recycler_view.mRecyclerView.computeVerticalScrollOffset() != 0){
                        sliding_layout.requestDisallowInterceptTouchEvent(true);
                    }
                }
            }
        });

Please advise me if you find any bugs or if this could be improved.
Thanks an have fun using.

**Comment by alexsorokoletov** [comment]
@dlukashev Dmitry, do you have your solution published? I was not able to make it work. Actually, item 4 is not clear

**Comment by dlukashev** [comment]
@alexsorokoletov Alex, I haven't tried to use this lib with RecyclerView... but I think it should be quite easy.

**Comment by alexsorokoletov** [comment]
@dlukashev I was not able to make it work. I would really appreciate if you can publish a simple example that works for your (either RecyclerView or something else used).

**Comment by dlukashev** [comment]
@alexsorokoletov oh, cmon. It is 15-minute change. Pushed to the master. Please tell me where do you have problems with it?

**Comment by alexsorokoletov** [comment]
I'm not that yet familiar with Android and Java, thank you for pushing this to master, let me look at it. 
Appreciate it!
