### ISSUE TITLE
android chat screen with google map using AndroidSlidingUpPanel Layout 

### ISSUE THREAD

**Issue by shushmit-yadav** [dlukashev/AndroidSlidingUpPanel-foursquare-map-demo#9]
My issue is I want google map in my 3/4 of screen and below map a listview and an EditText with Button.when we write into EditText and press button then message will appear into listview. and if we want see all listview then we want to slide map up show all listview. I am using map and listview as shown in AndroidSlidingUpPanel-foursquare-map-demo but i am not able to attach edit text and button.

![Uploading Screenshot_2015-07-09-11-54-00.png…]()

**Comment by dlukashev** [comment]
not clear
